export function paymentEnv() {
  return Object.fromEntries(['SUPABASE_URL','SUPABASE_ANON_KEY','SUPABASE_SERVICE_ROLE_KEY',
    'SUPABASE_SECRET_KEYS','SUPABASE_PUBLISHABLE_KEYS','SSLCOMMERZ_ENABLED','SSLCOMMERZ_ENVIRONMENT',
    'SSLCOMMERZ_CHECKOUT_ENABLED','SSLCOMMERZ_LIVE_APPROVED','SSLCOMMERZ_TIMESTAMP_ZONE',
    'SSLCOMMERZ_SANDBOX_STORE_ID','SSLCOMMERZ_SANDBOX_STORE_PASSWORD',
    'SSLCOMMERZ_LIVE_STORE_ID','SSLCOMMERZ_LIVE_STORE_PASSWORD','SSLCOMMERZ_RECONCILE_KEY']
    .map(name => [name,Deno.env.get(name) ?? '']));
}
