import {createClient} from '@supabase/supabase-js';import {parse} from 'tldts';
const $=id=>document.getElementById(id),states=['CONFIRMED','HIGH','SUSPECTED','MIRROR','DEAD','FALSE_POSITIVE','REVIEW_REQUIRED'];let db,page=0,selected;
const message=s=>$('notice').textContent=s;const run=f=>async()=>{try{await f();}catch(e){message(e.message||'Request failed');}};
const check=async q=>{const r=await q;if(r.error)throw r.error;return r;};
for(const id of ['state','decision'])for(const value of states){let option=document.createElement('option');option.value=option.textContent=value;$(id).append(option);}
async function authorize(){const {data:{user},error}=await db.auth.getUser();if(error||!user){$('login').hidden=false;$('admin').hidden=true;return;}if(user.app_metadata?.safenest_admin!==true){$('admin').hidden=true;throw Error('This account is not an intelligence administrator.');}$('admin').hidden=false;$('connect').hidden=true;await load();}
$('connectButton').onclick=run(async()=>{const key=$('key').value.trim();if(key.startsWith('sb_secret_'))throw Error('Use a public key only');if(key.split('.').length===3){try{const p=JSON.parse(atob(key.split('.')[1].replace(/-/g,'+').replace(/_/g,'/')));if(p.role==='service_role')throw Error('Never use a service-role key in this page');}catch(e){throw Error('Use a valid public key, not a service-role key');}}db=createClient($('url').value.trim(),key);await authorize();});
$('loginButton').onclick=run(async()=>{await check(db.auth.signInWithPassword({email:$('email').value,password:$('password').value}));$('password').value='';await authorize();});
$('logout').onclick=run(async()=>{await db.auth.signOut();location.reload();});
async function load(){let q=db.from('gambling_domains').select('id,domain,confidence,active,notes,brand_id').order('domain').range(page*50,page*50+49);const search=$('search').value.trim();if(search){if(!/^[a-z0-9.-]+$/i.test(search))throw Error('Search using hostname characters');q=q.ilike('domain','%'+search+'%');}if($('state').value)q=q.eq('confidence',$('state').value);const {data}=await check(q);$('rows').replaceChildren();for(const row of data){const tr=document.createElement('tr');for(const text of [row.domain,row.confidence,row.active?'Yes':'No']){const td=document.createElement('td');td.textContent=text;tr.append(td);}const td=document.createElement('td'),b=document.createElement('button');b.textContent='Review';b.onclick=run(()=>edit(row));td.append(b);tr.append(td);$('rows').append(tr);}const counts=await Promise.all(states.map(async s=>{const r=await check(db.from('gambling_domains').select('id',{count:'exact',head:true}).eq('confidence',s));return s+': '+r.count;}));$('stats').textContent=counts.join(' · ');const {data:release}=await check(db.from('blocklist_versions').select('version,domain_count,generated_at').order('version',{ascending:false}).limit(1));$('release').textContent=release.length?'Latest signed release: '+JSON.stringify(release[0]):'No signed release published';message('Page '+(page+1));}
async function edit(row){selected=row;$('editor').hidden=false;$('editing').textContent=row.domain;$('decision').value=row.confidence;$('active').checked=row.active;$('notes').value=row.notes;const {data:brands}=await check(db.from('gambling_brands').select('id,name').order('name').limit(1000));$('brand').replaceChildren(new Option('No brand',''));brands.forEach(b=>$('brand').add(new Option(b.name,b.id)));$('brand').value=row.brand_id||'';const {data:sources}=await check(db.from('domain_sources').select('source_name,source_url,evidence_summary,verified').eq('domain_id',row.id));$('evidence').textContent=sources.map(s=>`${s.verified?'Checked':'Unverified'}: ${s.source_name} — ${s.source_url}\n${s.evidence_summary}`).join('\n')||'No evidence yet';}
$('save').onclick=run(async()=>{if(!selected)return;const active=$('active').checked,confidence=$('decision').value;if(active&&!['CONFIRMED','HIGH','MIRROR'].includes(confidence))throw Error('Only confirmed, high confidence or verified mirrors may be active');await check(db.from('gambling_domains').update({confidence,active,brand_id:$('brand').value||null,notes:$('notes').value,last_verified:['CONFIRMED','HIGH','MIRROR'].includes(confidence)?new Date().toISOString():null}).eq('id',selected.id));await load();message('Saved. The publisher separately validates evidence before release.');});
$('addEvidence').onclick=run(async()=>{if(!selected)return;const u=new URL($('sourceUrl').value);if(u.protocol!=='https:'||u.username||u.password)throw Error('Use a public HTTPS evidence URL');await check(db.from('domain_sources').upsert({domain_id:selected.id,source_name:$('sourceName').value,source_url:u.href,source_type:$('sourceType').value,evidence_summary:$('summary').value,verified:$('verified').checked},{onConflict:'domain_id,source_url'}));await edit(selected);});
$('addAlias').onclick=run(async()=>{const alias=$('alias').value.trim();if(!$('brand').value||!alias)throw Error('Select brand and enter alias');await check(db.from('brand_aliases').upsert({brand_id:$('brand').value,alias,normalized_alias:alias.normalize('NFKC').toLowerCase().replace(/[^\p{L}\p{N}]/gu,'')},{onConflict:'brand_id,normalized_alias'}));message('Alias saved');});
$('add').onclick=run(async()=>{const raw=$('candidate').value.trim();const u=new URL(raw.includes('://')?raw:'https://'+raw);if(!['https:','http:'].includes(u.protocol)||u.username||u.password||u.port)throw Error('Invalid URL');const hostname=u.hostname.toLowerCase().replace(/\.$/,'');const p=parse(hostname,{allowPrivateDomains:true});if(!p.domain||p.isIp||(!p.isIcann&&!p.isPrivate))throw Error('Public hostname required');await check(db.from('gambling_domains').insert({domain:hostname.replace(/^www\./,''),registrable_domain:p.domain}));await load();});
$('searchButton').onclick=run(async()=>{page=0;await load();});$('prev').onclick=run(async()=>{page=Math.max(0,page-1);await load();});$('next').onclick=run(async()=>{page++;await load();});
