import { readFile, writeFile, readdir } from 'node:fs/promises';

const source = await readFile('website/index.html', 'utf8');
const header = source.match(/<header[\s\S]*?<\/header>/)[0].replace(/ aria-current=(?:"page"|page)/g, '');
const footer = source.match(/<footer[\s\S]*?<\/footer>/)[0];
const escape = value => value.replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('"', '&quot;');
const pair = (en, bn) => `<span data-en="${escape(en)}" data-bn="${escape(bn)}"><span class="translation-en" lang="en">${escape(en)}</span><span class="translation-bn" lang="bn">${escape(bn)}</span></span>`;
const block = (title, titleBn, en, bn) => `<section class="info-card"><h2>${pair(title, titleBn)}</h2><p>${pair(en, bn)}</p></section>`;
const pages = [
  ['contact', 'Contact SafeNest', 'SafeNest-এর সঙ্গে যোগাযোগ',
    block('Tell us what you need', 'কী সহায়তা দরকার জানান', 'Need help with the app, your account or a subscription? Send a private request from My SafeNest. Choose a topic, describe what happened and return to the same page to read replies. There is no promised response time during development.', 'অ্যাপ, অ্যাকাউন্ট বা সাবস্ক্রিপশন নিয়ে সহায়তা দরকার? My SafeNest থেকে ব্যক্তিগত অনুরোধ পাঠান। বিষয় বেছে কী হয়েছে লিখুন এবং উত্তর দেখতে একই পেজে ফিরুন। পরীক্ষামূলক পর্যায়ে নির্দিষ্ট সময়ের মধ্যে উত্তরের প্রতিশ্রুতি নেই।') +
    '<p><a class="btn dark" href="account.html#support">' + pair('Send a support request', 'সহায়তার অনুরোধ পাঠান') + '</a></p>' +
    block('App and account help', 'অ্যাপ ও অ্যাকাউন্টের সহায়তা', 'Include your Android version, SafeNest version, whether you use Wi-Fi or mobile data and the exact error message. Leave out passwords, reset links and your browsing history. If you cannot sign in, try the password reset on the account page. Requests currently require a confirmed account; an email route for people who cannot access their account is still being set up.', 'Android ও SafeNest-এর সংস্করণ, Wi-Fi না মোবাইল ডেটা এবং ত্রুটির বার্তা দিন। পাসওয়ার্ড, রিসেট লিংক ও ব্রাউজিংয়ের ইতিহাস দেবেন না। লগইন না হলে অ্যাকাউন্ট পেজে পাসওয়ার্ড রিসেট চেষ্টা করুন। অনুরোধের জন্য বর্তমানে নিশ্চিত অ্যাকাউন্ট দরকার; অ্যাকাউন্ট ব্যবহার করতে না পারলে যোগাযোগের ইমেইল এখনো প্রস্তুত হচ্ছে।') +
    block('Billing and subscriptions', 'বিলিং ও সাবস্ক্রিপশন', 'Choose Billing & subscriptions for plan or access-period questions. Checkout and automatic charging are not open. Do not send money to a personal wallet or share a card number, PIN or one-time code in a support message.', 'প্ল্যান বা মেয়াদের প্রশ্নে Billing & subscriptions বেছে নিন। চেকআউট ও স্বয়ংক্রিয় চার্জ চালু নয়। সহায়তার বার্তায় কার্ড নম্বর, PIN বা একবারের কোড দেবেন না এবং ব্যক্তিগত ওয়ালেটে টাকা পাঠাবেন না।') +
    '<p><a href="account.html?topic=billing#support">' + pair('Ask about billing', 'বিলিং নিয়ে প্রশ্ন করুন') + '</a> · <a href="pricing.html">' + pair('View plans', 'প্ল্যান দেখুন') + '</a></p>' +
    block('Privacy and account deletion', 'গোপনীয়তা ও অ্যাকাউন্ট মুছে ফেলা', 'Choose Privacy & deletion for a question about your information. You can delete your account yourself from My SafeNest after password confirmation. Messages are stored with your account and are visible to you and authorized SafeNest support. Deletion removes the conversations from the live database; final infrastructure backup and log retention periods remain unconfirmed.', 'আপনার তথ্য নিয়ে প্রশ্নে Privacy & deletion বেছে নিন। পাসওয়ার্ড নিশ্চিত করে My SafeNest থেকে নিজেই অ্যাকাউন্ট মুছতে পারবেন। বার্তা অ্যাকাউন্টের সঙ্গে থাকে এবং আপনি ও অনুমোদিত SafeNest সহায়তা কর্মী দেখতে পারেন। মুছলে বর্তমান ডেটাবেসের কথোপকথন মুছে যায়; অবকাঠামোর ব্যাকআপ ও লগ রাখার চূড়ান্ত সময় এখনো নিশ্চিত নয়।') +
    '<p><a href="account.html?topic=privacy#support">' + pair('Ask a privacy question', 'গোপনীয়তা নিয়ে প্রশ্ন করুন') + '</a> · <a href="delete-account.html">' + pair('Delete my account', 'আমার অ্যাকাউন্ট মুছুন') + '</a></p>' +
    block('Business enquiries', 'ব্যবসায়িক যোগাযোগ', 'Choose Business enquiries for partnership or general business questions.', 'অংশীদারিত্ব বা সাধারণ ব্যবসায়িক প্রশ্নে Business enquiries বেছে নিন।') +
    '<p><a href="account.html?topic=business#support">' + pair('Send a business enquiry', 'ব্যবসায়িক বার্তা পাঠান') + '</a></p>' +
    block('Business email is being set up', 'ব্যবসার ইমেইল প্রস্তুত হচ্ছে', 'We will publish a branded support email after receiving and replying have been verified. Authentication emails come from a no-reply address; replying to them is not a support request. There is no public phone, WhatsApp or social support channel at present. Replies to portal requests appear in My SafeNest; email notifications are not active.', 'বার্তা গ্রহণ ও উত্তর দেওয়া যাচাই হলে ব্যবসার সহায়তার ইমেইল প্রকাশ করা হবে। অ্যাকাউন্টের ইমেইল no-reply ঠিকানা থেকে আসে; সেখানে উত্তর পাঠালে সহায়তার অনুরোধ হয় না। বর্তমানে প্রকাশ্য ফোন, WhatsApp বা সামাজিক যোগাযোগের সহায়তা নেই। পোর্টালের অনুরোধের উত্তর My SafeNest-এ থাকে; ইমেইল নোটিফিকেশন চালু নয়।')],

  ['delete-account', 'Delete your SafeNest account', 'আপনার SafeNest অ্যাকাউন্ট মুছুন',
    block('Delete without reinstalling the app', 'অ্যাপ আবার ইনস্টল না করেই মুছুন', 'Sign in to your SafeNest account below. Open “Delete my SafeNest account”, confirm your current password and tick the permanent-deletion confirmation. Your account, optional profile and server protection entitlement are deleted. Forgotten your password? Use the reset link on the sign-in page first.', 'নিচে SafeNest অ্যাকাউন্টে লগইন করুন। “আমার SafeNest অ্যাকাউন্ট মুছুন” খুলে বর্তমান পাসওয়ার্ড ও স্থায়ীভাবে মুছে দেওয়ার সম্মতি দিন। অ্যাকাউন্ট, ঐচ্ছিক প্রোফাইল ও সার্ভারের সুরক্ষার অনুমতি মুছে যাবে। পাসওয়ার্ড ভুলে গেলে লগইন পেজে রিসেট লিংক নিন।') +
    '<p><a class="btn dark" href="account.html#delete-account">' + pair('Sign in to delete my account', 'লগইন করে আমার অ্যাকাউন্ট মুছুন') + '</a></p>' +
    block('What remains on your phone', 'ফোনে কী থাকে', 'This removes server account data. It does not uninstall SafeNest or erase locally stored lists and check-ins. The app can hold a previously verified period offline until expiry; deleting the account is not an immediate device unlock. A future consumer Play release must keep Android uninstall and permission controls available.', 'এটি সার্ভারের অ্যাকাউন্ট তথ্য মুছে দেয়। SafeNest আনইনস্টল করে না বা ফোনের স্থানীয় তালিকা ও চেক-ইন মুছে দেয় না। আগে যাচাইকৃত মেয়াদ অফলাইনে শেষ পর্যন্ত থাকতে পারে; অ্যাকাউন্ট মুছলে ফোন সঙ্গে সঙ্গে আনলক হয় না। ভবিষ্যতের সাধারণ Play সংস্করণে Android-এর আনইনস্টল ও অনুমতির নিয়ন্ত্রণ খোলা রাখতে হবে।') +
    block('Subscriptions and retention', 'সাবস্ক্রিপশন ও তথ্য সংরক্ষণ', 'Payments are not active yet. When subscriptions become available, cancellation and deletion will be separate actions. Any required transaction retention and backup deletion schedule will be disclosed before paid sales open. Current deletion removes the account-linked rows from the live database immediately after successful confirmation.', 'পেমেন্ট এখনো চালু নয়। সাবস্ক্রিপশন চালু হলে বাতিল ও অ্যাকাউন্ট মুছতে আলাদা কাজ করতে হবে। প্রয়োজনীয় লেনদেন ও ব্যাকআপ সংরক্ষণের সময় বিক্রি শুরু হওয়ার আগে জানানো হবে। সফল নিশ্চিতকরণের পরে বর্তমান ডেটাবেসের অ্যাকাউন্ট-সংশ্লিষ্ট তথ্য সঙ্গে সঙ্গে মুছে যায়।')],
  ['privacy', 'SafeNest privacy information', 'SafeNest-এর গোপনীয়তার তথ্য',
    block('Current service · updated 7 October 2026', 'বর্তমান সেবা · ৭ অক্টোবর ২০২৬', 'SafeNest is currently a website and Android development application. This notice describes the current service. Use the contact page for private support and privacy requests. Business identity, a verified business email and the final retention schedule must be completed before paid public release.', 'SafeNest বর্তমানে একটি ওয়েবসাইট ও Android পরীক্ষামূলক অ্যাপ। এই নোটিশ বর্তমান সেবার তথ্য জানায়। পেইড প্রকাশের আগে ব্যবসার পরিচয়, যাচাইকৃত ব্যবসার ইমেইল এবং চূড়ান্ত তথ্য সংরক্ষণের সময় নির্ধারণ করতে হবে। ব্যক্তিগত সহায়তা ও গোপনীয়তার অনুরোধে যোগাযোগ পেজ ব্যবহার করুন।') +
    block('Accounts and emails', 'অ্যাকাউন্ট ও ইমেইল', 'Supabase processes email, password authentication and sessions. The database stores your optional display name, language, server-issued protection periods, trial claim and selected plan. The account-linked trial claim is deleted with the account; this does not establish a one-person anti-abuse guarantee. Resend delivers confirmation and recovery emails. The website keeps a login session in browser storage. Never share your password or email reset link.', 'Supabase ইমেইল, পাসওয়ার্ড যাচাই ও লগইন সেশন পরিচালনা করে। ডেটাবেসে ঐচ্ছিক নাম, ভাষা, সার্ভারের সুরক্ষার মেয়াদ, ট্রায়াল ও নির্বাচিত প্ল্যান থাকে। অ্যাকাউন্ট মুছলে সংশ্লিষ্ট ট্রায়াল তথ্যও মুছে যায়; এটি এক ব্যক্তি একবারের অপব্যবহার-প্রতিরোধের নিশ্চয়তা নয়। Resend নিশ্চিতকরণ ও পাসওয়ার্ড রিসেট ইমেইল পাঠায়। ওয়েবসাইট ব্রাউজারে লগইন সেশন রাখে। পাসওয়ার্ড বা রিসেট লিংক শেয়ার করবেন না।') +
    block('Support messages', 'সহায়তার বার্তা', 'Private support requests store your chosen topic, subject, message text, timestamps and replies with your account in Supabase. Only you and authorized SafeNest support can read the conversation. Messages are not public and email notifications are not active. Account deletion removes these conversations from the live database. Final backup and operational-log retention periods remain unconfirmed.', 'ব্যক্তিগত সহায়তার অনুরোধে বিষয়, শিরোনাম, বার্তা, সময় ও উত্তর Supabase-এ আপনার অ্যাকাউন্টের সঙ্গে থাকে। শুধু আপনি ও অনুমোদিত SafeNest সহায়তা কর্মী কথোপকথন পড়তে পারেন। বার্তা প্রকাশ্য নয় এবং ইমেইল নোটিফিকেশন চালু নেই। অ্যাকাউন্ট মুছলে বর্তমান ডেটাবেসের কথোপকথন মুছে যায়। ব্যাকআপ ও কার্যক্রমের লগ রাখার চূড়ান্ত সময় এখনো নিশ্চিত নয়।') +
    '<p><a href="contact.html">' + pair('Contact SafeNest about privacy', 'গোপনীয়তা নিয়ে SafeNest-এর সঙ্গে যোগাযোগ') + '</a></p>' +
    block('Website requests', 'ওয়েবসাইটের অনুরোধ', 'Website assets are served through Sites hosting. Google Fonts may receive ordinary web requests. The website itself does not filter DNS or protect your device.', 'Sites হোস্টিং থেকে ওয়েবসাইটের ফাইল আসে। Google Fonts সাধারণ ওয়েব অনুরোধ পেতে পারে। ওয়েবসাইট নিজে DNS ফিল্টার করে না বা ডিভাইসে সুরক্ষা চালু করে না।') +
    block('DNS in Android 0.4.7', 'Android ০.৪.৭-এর DNS', 'The 0.4.7 source checks domain rules locally before forwarding allowed DNS queries over certificate- and hostname-verified HTTPS to Cloudflare. Cloudflare receives the allowed domain names and your network IP address; no SafeNest account token, password or cookie is added to these requests. On Android 10 or later, an explicitly selected strict Private DNS provider is used through Android instead, once validated. That provider receives the queries. If encrypted resolution fails, the query fails; SafeNest does not retry over plain UDP/TCP DNS or switch a strict provider to Cloudflare or Google. Automatic Private DNS does not provide the same strict guarantee, so this path uses Cloudflare HTTPS.', '০.৪.৭-এর সোর্স প্রথমে ফোনে ডোমেইনের নিয়ম পরীক্ষা করে। অনুমোদিত DNS অনুরোধ সনদ ও হোস্টনেম যাচাইকৃত HTTPS দিয়ে Cloudflare-এ যায়। Cloudflare অনুমোদিত ডোমেইনের নাম ও নেটওয়ার্কের IP পায়; এসব অনুরোধে SafeNest-এর অ্যাকাউন্ট টোকেন, পাসওয়ার্ড বা কুকি যোগ হয় না। Android ১০ বা পরবর্তী সংস্করণে নির্দিষ্ট strict Private DNS সেবা বেছে নিলে, যাচাইয়ের পরে Android-এর মাধ্যমে সেই সেবা ব্যবহার হয় এবং সেটি অনুরোধ পায়। এনক্রিপ্টেড DNS ব্যর্থ হলে অনুরোধ ব্যর্থ হয়; সাধারণ UDP/TCP DNS-এ আবার পাঠানো হয় না বা strict সেবার বদলে Cloudflare বা Google নেওয়া হয় না। Automatic Private DNS একই নিশ্চয়তা দেয় না, তাই এ ক্ষেত্রে Cloudflare HTTPS ব্যবহার হয়।') +
    block('Version and protection limits', 'সংস্করণ ও সুরক্ষার সীমা', 'The website download is the 0.4.9 direct development APK, with the selected Raspberry Pink branding and opening animation. Compilation and lint checks do not establish live protection, trial acceptance or a verified customer release. SafeNest uses a DNS-based local VPN interface; ordinary internet traffic stays on Android’s normal network routes. It does not tunnel all traffic or decrypt and inspect HTTPS pages. Independent browser Secure DNS, direct-IP access, proxies, cached connections, another VPN and revoked permissions can bypass or stop filtering. Resolver encryption is not complete coverage, anonymity or Google Play approval. Resolver log and backup retention periods remain unconfirmed; final periods must be disclosed before paid launch.', 'ওয়েবসাইটে নির্বাচিত Raspberry Pink লোগো ও শুরুর অ্যানিমেশনসহ ০.৪.৯ direct পরীক্ষামূলক APK আছে। কম্পাইল ও lint পরীক্ষা লাইভ সুরক্ষা, ট্রায়াল বা যাচাইকৃত গ্রাহক সংস্করণের প্রমাণ নয়। SafeNest DNS-ভিত্তিক স্থানীয় VPN ইন্টারফেস ব্যবহার করে; সাধারণ ইন্টারনেট Android-এর স্বাভাবিক নেটওয়ার্ক পথে চলে। সব ট্রাফিক টানেল করে না বা HTTPS পৃষ্ঠা ডিক্রিপ্ট করে পরীক্ষা করে না। ব্রাউজারের আলাদা Secure DNS, সরাসরি IP, প্রক্সি, ক্যাশ করা সংযোগ, অন্য VPN বা অনুমতি প্রত্যাহার ফিল্টার এড়াতে বা বন্ধ করতে পারে। DNS এনক্রিপশন সম্পূর্ণ কভারেজ, পরিচয় গোপন রাখা বা Google Play অনুমোদনের প্রমাণ নয়। DNS সেবার লগ ও ব্যাকআপ রাখার সময় এখনো নিশ্চিত নয়; পেইড প্রকাশের আগে চূড়ান্ত সময় জানাতে হবে।') +
    block('App guard and local information', 'অ্যাপ গার্ড ও ফোনের তথ্য', 'The current Android development build uses consented Accessibility to identify foreground app package IDs, selected blocked apps, detected VPN apps, supported address bars and narrow Settings/installer labels. A separate consumer Play build is still required and must keep uninstall and permission controls usable. Those observations are not recorded or uploaded. Local lists, check-ins and protection state stay on the phone. No advertising or analytics SDK is included in the current Android source.', 'বর্তমান পরীক্ষামূলক Android সংস্করণ সম্মতির পরে Accessibility দিয়ে অ্যাপের ID, নির্বাচিত ব্লক অ্যাপ, শনাক্ত VPN অ্যাপ, সমর্থিত ঠিকানা ও সীমিত সেটিংস বা ইনস্টলার লেবেল দেখে। আলাদা সাধারণ Play সংস্করণ এখনো তৈরি করতে হবে এবং সেখানে আনইনস্টল ও অনুমতির নিয়ন্ত্রণ খোলা রাখতে হবে। এই পর্যবেক্ষণ সংরক্ষণ বা আপলোড হয় না। স্থানীয় তালিকা, চেক-ইন ও সুরক্ষার অবস্থা ফোনেই থাকে। বর্তমান Android সোর্সে বিজ্ঞাপন বা অ্যানালিটিক্স SDK নেই।') +
    block('Deletion and choices', 'মুছে ফেলা ও আপনার পছন্দ', 'You can request permanent account deletion through the account page without reinstalling the app. It requires password confirmation and deletes the live account, profile and server entitlement. Technical infrastructure may retain operational logs or backups under its configured retention; exact periods must be finalized before launch. SafeNest payments, card collection and crypto checkout are not active.', 'অ্যাপ আবার ইনস্টল না করেই অ্যাকাউন্ট পেজে স্থায়ীভাবে মুছতে পারবেন। পাসওয়ার্ড নিশ্চিত করলে বর্তমান অ্যাকাউন্ট, প্রোফাইল ও সার্ভারের অনুমতি মুছে যাবে। হোস্টিং সেবার নির্ধারিত সময় পর্যন্ত প্রযুক্তিগত লগ বা ব্যাকআপ থাকতে পারে; প্রকাশের আগে সময় নিশ্চিত করতে হবে। SafeNest-এর পেমেন্ট, কার্ড গ্রহণ ও ক্রিপ্টো চেকআউট চালু নয়।') +
    '<p><a href="delete-account.html">' + pair('Delete account instructions', 'অ্যাকাউন্ট মুছে ফেলার নির্দেশিকা') + '</a> · <a href="support.html">' + pair('Service help', 'সেবার সহায়তা') + '</a></p>'],
  ['terms', 'SafeNest service terms and status', 'SafeNest-এর শর্ত ও বর্তমান অবস্থা',
    block('Development service', 'পরীক্ষামূলক সেবা', 'The website is live and the Android application is under testing. Pricing is proposed; purchases and automatic renewals are not active. Do not rely on this development build as your only protection. It cannot promise that every gambling site, adult site, VPN or proxy is blocked.', 'ওয়েবসাইট চালু এবং Android অ্যাপ পরীক্ষাধীন। মূল্য প্রস্তাবিত; কেনা বা স্বয়ংক্রিয় নবায়ন চালু নয়। পরীক্ষামূলক অ্যাপকে একমাত্র সুরক্ষা ধরে নেবেন না। সব জুয়া, প্রাপ্তবয়স্ক সাইট, VPN বা প্রক্সি ব্লক হওয়ার প্রতিশ্রুতি নেই।') +
    block('Network behavior and limits', 'নেটওয়ার্কের আচরণ ও সীমা', 'SafeNest is a DNS-based filter, not a full traffic-inspection or privacy VPN. The 0.4.7 source uses verified HTTPS DNS or validated strict system Private DNS, with no plain-DNS fallback. An encrypted resolver failure can prevent allowed names from resolving. Android 9 strict Private DNS is unsupported by this filter; startup is refused or filtering stops if that configuration is detected. Ordinary traffic is not tunneled. Browser Secure DNS, proxies, direct-IP access, cached connections and VPN replacement remain limitations. The downloadable 0.4.0 APK is older; a signed, tested 0.4.7 customer release and Play approval remain pending.', 'SafeNest DNS-ভিত্তিক ফিল্টার; সব ট্রাফিক পরীক্ষা বা পরিচয় গোপন রাখার VPN নয়। ০.৪.৭-এর সোর্স যাচাইকৃত HTTPS DNS বা যাচাইকৃত strict সিস্টেম Private DNS ব্যবহার করে; সাধারণ DNS বিকল্প নেই। এনক্রিপ্টেড DNS ব্যর্থ হলে অনুমোদিত নামও সমাধান না হতে পারে। এই ফিল্টারে Android ৯-এর strict Private DNS সমর্থিত নয়; শনাক্ত হলে শুরু হয় না বা ফিল্টার বন্ধ হয়। সাধারণ ট্রাফিক টানেল হয় না। ব্রাউজারের Secure DNS, প্রক্সি, সরাসরি IP, ক্যাশ করা সংযোগ ও অন্য VPN-এর সীমাবদ্ধতা থাকে। ডাউনলোডের ০.৪.০ APK পুরোনো; সাইন করা ও পরীক্ষিত ০.৪.৭ গ্রাহক সংস্করণ এবং Play অনুমোদন এখনো বাকি।') +
    block('Permission and finite protection', 'অনুমতি ও নির্দিষ্ট মেয়াদের সুরক্ষা', 'Protection requires separate informed consent and a server-verified active period. Once started, this app has no in-app pause during that period and expires automatically. Android may revoke permissions or stop the application. A future consumer Play build must leave uninstall and Settings controls usable. Managed-device controls require separate authorized enrollment.', 'সুরক্ষা চালু করতে আলাদা সচেতন সম্মতি ও সার্ভারে যাচাইকৃত মেয়াদ দরকার। চালুর পরে অ্যাপে বিরতি নেই এবং মেয়াদ শেষে স্বয়ংক্রিয়ভাবে শেষ হয়। Android অনুমতি ফিরিয়ে নিতে বা অ্যাপ বন্ধ করতে পারে। ভবিষ্যতের সাধারণ Play সংস্করণে আনইনস্টল ও সেটিংস খোলা রাখতে হবে। পরিচালিত ডিভাইসের নিয়ন্ত্রণের জন্য আলাদা অনুমোদিত নিবন্ধন লাগে।') +
    block('Trials, expiry and renewal', 'ট্রায়াল, মেয়াদ ও নবায়ন', 'The planned trial is 72 hours, once per confirmed account, starting only when requested. Trial enrolment is held for compatible Android release testing. Planned paid access is ৳379 for 30 days, ৳999 for 90 days or ৳3,799 for 365 days. Server time and verified access windows decide eligibility; protection stops at expiry. Starting a trial or selecting a plan does not authorize a debit. Payment-method verification and automatic renewal are not active. A future recurring-payment flow must show the amount, first charge date, cycle and cancellation steps and obtain separate authorization. If payment is unverified or fails, paid access is not issued. The app must verify each new period; a cached offline period does not silently extend.', 'পরিকল্পিত ট্রায়াল ৭২ ঘণ্টা, নিশ্চিত অ্যাকাউন্টে একবার; অনুরোধ করলে শুরু হয়। উপযুক্ত Android সংস্করণের পরীক্ষার জন্য ট্রায়াল নিবন্ধন বন্ধ আছে। পরিকল্পিত পেইড মেয়াদ ৩০ দিনে ৳৩৭৯, ৯০ দিনে ৳৯৯৯ বা ৩৬৫ দিনে ৳৩,৭৯৯। সার্ভারের সময় ও যাচাইকৃত মেয়াদ দিয়ে অনুমতি নির্ধারিত হয়; মেয়াদ শেষে সুরক্ষা বন্ধ হয়। ট্রায়াল বা প্ল্যান বেছে নিলে টাকা কাটার অনুমতি হয় না। পেমেন্ট মাধ্যম যাচাই ও স্বয়ংক্রিয় নবায়ন চালু নয়। ভবিষ্যতে আলাদা সম্মতির আগে মূল্য, প্রথম চার্জের তারিখ, চক্র ও বাতিলের ধাপ দেখাতে হবে। পেমেন্ট যাচাই না হলে বা ব্যর্থ হলে পেইড অনুমতি দেওয়া হয় না। নতুন মেয়াদ অ্যাপে যাচাই করতে হবে; অফলাইনে রাখা মেয়াদ নিজে থেকে বাড়ে না।') +
    block('Before paid launch', 'পেইড প্রকাশের আগে', 'Final seller identity, a verified business email, prices, taxes, device limits, cancellation/refund rules and transaction retention must be published before checkout opens. No payment reference or success page alone can activate protection; the server must verify the payment provider receipt.', 'চেকআউট চালুর আগে বিক্রেতার পরিচয়, যাচাইকৃত ব্যবসার ইমেইল, মূল্য, কর, ডিভাইস সীমা, বাতিল ও রিফান্ডের নিয়ম এবং লেনদেন সংরক্ষণের সময় প্রকাশ করতে হবে। শুধু পেমেন্ট নম্বর বা সফল পেজ দিয়ে সুরক্ষা চালু হবে না; সার্ভারে পেমেন্ট সেবার রসিদ যাচাই করতে হবে।')],
  ['checkout', 'SafeNest payments', 'SafeNest পেমেন্ট',
    block('Checkout is not open yet', 'চেকআউট এখনো চালু নয়', 'No payment is collected on this page. Monthly, three-month and yearly prices are on the pricing page. We will open checkout only after verified receipts, refunds, cancellation and activation have been tested.', 'এই পেজে পেমেন্ট নেওয়া হয় না। মাসিক, তিন মাস ও বার্ষিক মূল্য মূল্যতালিকায় আছে। রসিদ যাচাই, রিফান্ড, বাতিল ও সুরক্ষা চালু করার পরীক্ষা শেষ হলে চেকআউট খুলবে।') +
    block('Planned payment options', 'পরিকল্পিত পেমেন্ট মাধ্যম', 'International cards and Bangladesh mobile wallets such as bKash, Nagad, Rocket and upay need an approved merchant/payment gateway account. Logos show planned methods, not live integrations. Cryptocurrency is not currently accepted. The Android development app currently serves existing accounts and has no purchase button.', 'আন্তর্জাতিক কার্ড এবং bKash, Nagad, Rocket ও upay-এর জন্য অনুমোদিত মার্চেন্ট বা পেমেন্ট গেটওয়ে অ্যাকাউন্ট দরকার। লোগো পরিকল্পিত মাধ্যম দেখায়; সংযোগ চালু নয়। ক্রিপ্টোকারেন্সি বর্তমানে গ্রহণ করা হয় না। পরীক্ষামূলক Android অ্যাপ বিদ্যমান অ্যাকাউন্ট ব্যবহার করে; অ্যাপে কেনার বোতাম নেই।') +
    '<p><a class="btn dark" href="pricing.html">' + pair('View proposed plans', 'প্রস্তাবিত প্ল্যান দেখুন') + '</a></p>'],
  ['support', 'SafeNest help and release status', 'SafeNest সহায়তা ও প্রকাশের অবস্থা',
    '<p><a class="btn dark" href="contact.html">' + pair('Contact SafeNest', 'SafeNest-এর সঙ্গে যোগাযোগ') + '</a></p>' +
    block('If ordinary browsing stops', 'সাধারণ ব্রাউজিং বন্ধ হলে', 'This DNS-only build must leave Android’s “Block connections without VPN” off. Test a normal website and a listed test domain on both Wi-Fi and mobile data. Another active VPN can replace SafeNest on a personal phone; the status screen should report it.', 'এই DNS-only সংস্করণে Android-এর “Block connections without VPN” বন্ধ রাখতে হবে। Wi-Fi ও মোবাইল ডেটায় সাধারণ সাইট ও তালিকার পরীক্ষার ডোমেইন দেখুন। ব্যক্তিগত ফোনে অন্য সক্রিয় VPN SafeNest-কে বদলে দিতে পারে; অবস্থা পেজে তা দেখানোর কথা।') +
    block('Encrypted DNS troubleshooting in 0.4.7', '০.৪.৭-এর এনক্রিপ্টেড DNS সমস্যা', 'Check the app’s DNS transport, health and error status as well as its VPN permission. With Private DNS off or Automatic, allowed names use Cloudflare HTTPS. With a strict provider on Android 10 or later, verify that provider is reachable and validated. If it fails, DNS queries fail without a plain fallback or an alternate provider. Restore network access and review your chosen provider in Android Settings. Android 9 strict Private DNS is unsupported and prevents startup or stops filtering. A running notification alone does not prove protection; test normal browsing and a listed domain after network changes. These instructions describe 0.4.7 source; the website’s older 0.4.0 test APK does not establish this behavior.', 'অ্যাপের DNS transport, health ও error এবং VPN অনুমতি দেখুন। Private DNS বন্ধ বা Automatic হলে অনুমোদিত নাম Cloudflare HTTPS দিয়ে যায়। Android ১০ বা পরবর্তী সংস্করণে strict সেবা ব্যবহার করলে সেটি সচল ও যাচাইকৃত কি না দেখুন। ব্যর্থ হলে সাধারণ DNS বা অন্য সেবা নেওয়া হয় না; DNS অনুরোধ ব্যর্থ হয়। নেটওয়ার্ক ঠিক করে Android Settings-এ বেছে নেওয়া সেবা পরীক্ষা করুন। Android ৯-এর strict Private DNS সমর্থিত নয়; শুরু হতে বাধা দেয় বা ফিল্টার বন্ধ করে। শুধু নোটিফিকেশন চললেই সুরক্ষা নিশ্চিত নয়; নেটওয়ার্ক বদলালে সাধারণ সাইট ও তালিকার ডোমেইন পরীক্ষা করুন। এটি ০.৪.৭-এর সোর্সের নির্দেশনা; ওয়েবসাইটের পুরোনো ০.৪.০ পরীক্ষামূলক APK এই আচরণের প্রমাণ নয়।') +
    block('What this filter can miss', 'ফিল্টার যা এড়িয়ে যেতে পারে', 'This local DNS interface does not relay or inspect all internet traffic. Browser Secure DNS, direct-IP requests, proxies and cached connections can avoid its DNS route. Another VPN or Android permission revocation can stop filtering. Complete blocking and Play approval are not claimed.', 'এই স্থানীয় DNS ইন্টারফেস সব ইন্টারনেট ট্রাফিক বহন বা পরীক্ষা করে না। ব্রাউজারের Secure DNS, সরাসরি IP, প্রক্সি ও ক্যাশ করা সংযোগ DNS পথ এড়াতে পারে। অন্য VPN বা Android-এর অনুমতি প্রত্যাহারে ফিল্টার বন্ধ হতে পারে। সম্পূর্ণ ব্লকিং বা Play অনুমোদনের দাবি নেই।') +
    block('Trial and subscription status', 'ট্রায়াল ও সাবস্ক্রিপশনের অবস্থা', 'Use My SafeNest to check your verified period and exact end time. Protection stops when the trial or paid period ends. Trial enrolment is awaiting a compatible tested Android update; the older 0.4.0 download is not a trial release. Payment verification and automatic charging are not open yet.', 'My SafeNest-এ যাচাইকৃত মেয়াদ ও শেষের সময় দেখুন। ট্রায়াল বা পেইড মেয়াদ শেষে সুরক্ষা বন্ধ হয়। উপযুক্ত পরীক্ষিত Android আপডেটের অপেক্ষায় ট্রায়াল বন্ধ; পুরোনো ০.৪.০ ডাউনলোড ট্রায়াল সংস্করণ নয়। পেমেন্ট যাচাই ও স্বয়ংক্রিয় চার্জ এখনো চালু নয়।') +
    block('Account access', 'অ্যাকাউন্ট ব্যবহার', 'Use the account page to confirm your email, reset a forgotten password or delete the account. For a private support request, use the contact page. Replies appear in My SafeNest; business email is still being configured. Never send passwords, authentication tokens or private browsing details in public comments.', 'অ্যাকাউন্ট পেজে ইমেইল নিশ্চিত করুন, ভুলে যাওয়া পাসওয়ার্ড রিসেট করুন বা অ্যাকাউন্ট মুছুন। ব্যক্তিগত সহায়তার অনুরোধে যোগাযোগ পেজ ব্যবহার করুন। উত্তর My SafeNest-এ আসে; ব্যবসার ইমেইল এখনো প্রস্তুত হচ্ছে। পাবলিক মন্তব্যে পাসওয়ার্ড, লগইন টোকেন বা ব্যক্তিগত ব্রাউজিংয়ের তথ্য দেবেন না।') +
    '<p><a href="account.html">' + pair('Open my account', 'আমার অ্যাকাউন্ট খুলুন') + '</a> · <a href="delete-account.html">' + pair('Delete my account', 'আমার অ্যাকাউন্ট মুছুন') + '</a></p>']
];
for (const [slug, title, bn, body] of pages) {
  await writeFile(`dist/${slug}.html`, `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="referrer" content="no-referrer"><title>${escape(title)}</title><link rel="icon" href="assets/brand/favicon.png" type="image/png"><link rel="apple-touch-icon" href="assets/brand/apple-touch-icon.png"><link rel="stylesheet" href="styles.css"><link rel="stylesheet" href="liquid-pink.css"><link rel="stylesheet" href="brand.css"><link rel="stylesheet" href="editorial.css"><link rel="stylesheet" href="payment-footer.css"></head><body>${header}<main class="page-body" id="main"><section class="page-intro"><h1>${pair(title,bn)}</h1></section>${body}</main>${footer}<script src="app.js" defer></script><script src="liquid-pink.js" defer></script></body></html>`);
}
const legal = `<nav aria-label="Service information"><a href="privacy.html">${pair('Privacy','গোপনীয়তা')}</a><a href="terms.html">${pair('Terms','শর্তাবলি')}</a><a href="delete-account.html">${pair('Delete account','অ্যাকাউন্ট মুছুন')}</a><a href="support.html">${pair('Help','সহায়তা')}</a><a href="contact.html">${pair('Contact','যোগাযোগ')}</a></nav>`;
for (const file of await readdir('dist')) {
  if (!file.endsWith('.html') || file === 'account.html') continue;
  const path = `dist/${file}`;
  const html = (await readFile(path, 'utf8')).replaceAll('href="./#privacy"', 'href="privacy.html"').replace('</footer>', `${legal}</footer>`);
  await writeFile(path, html);
}
