import { readFile, writeFile, readdir } from 'node:fs/promises';

const source = await readFile('website/index.html', 'utf8');
const header = source.match(/<header[\s\S]*?<\/header>/)[0];
const footer = source.match(/<footer[\s\S]*?<\/footer>/)[0];
const escape = value => value.replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('"', '&quot;');
const pair = (en, bn) => `<span data-en="${escape(en)}" data-bn="${escape(bn)}"><span class="translation-en" lang="en">${escape(en)}</span><span class="translation-bn" lang="bn">${escape(bn)}</span></span>`;
const block = (title, titleBn, en, bn) => `<section class="info-card"><h2>${pair(title, titleBn)}</h2><p>${pair(en, bn)}</p></section>`;
const pages = [
  ['delete-account', 'Delete your SafeNest account', 'আপনার SafeNest অ্যাকাউন্ট মুছুন',
    block('Delete without reinstalling the app', 'অ্যাপ আবার ইনস্টল না করেই মুছুন', 'Sign in to your SafeNest account below. Open “Delete my SafeNest account”, confirm your current password and tick the permanent-deletion confirmation. Your account, optional profile and server protection entitlement are deleted. Forgotten your password? Use the reset link on the sign-in page first.', 'নিচে SafeNest অ্যাকাউন্টে লগইন করুন। “আমার SafeNest অ্যাকাউন্ট মুছুন” খুলে বর্তমান পাসওয়ার্ড ও স্থায়ীভাবে মুছে দেওয়ার সম্মতি দিন। অ্যাকাউন্ট, ঐচ্ছিক প্রোফাইল ও সার্ভারের সুরক্ষার অনুমতি মুছে যাবে। পাসওয়ার্ড ভুলে গেলে লগইন পেজে রিসেট লিংক নিন।') +
    '<p><a class="btn dark" href="account.html#delete-account">' + pair('Sign in to delete my account', 'লগইন করে আমার অ্যাকাউন্ট মুছুন') + '</a></p>' +
    block('What remains on your phone', 'ফোনে কী থাকে', 'This removes server account data. It does not uninstall SafeNest or erase locally stored lists and check-ins. The app can hold a previously verified period offline until expiry; deleting the account is not an immediate device unlock. A future consumer Play release must keep Android uninstall and permission controls available.', 'এটি সার্ভারের অ্যাকাউন্ট তথ্য মুছে দেয়। SafeNest আনইনস্টল করে না বা ফোনের স্থানীয় তালিকা ও চেক-ইন মুছে দেয় না। আগে যাচাইকৃত মেয়াদ অফলাইনে শেষ পর্যন্ত থাকতে পারে; অ্যাকাউন্ট মুছলে ফোন সঙ্গে সঙ্গে আনলক হয় না। ভবিষ্যতের সাধারণ Play সংস্করণে Android-এর আনইনস্টল ও অনুমতির নিয়ন্ত্রণ খোলা রাখতে হবে।') +
    block('Subscriptions and retention', 'সাবস্ক্রিপশন ও তথ্য সংরক্ষণ', 'Payments are not active yet. When subscriptions become available, cancellation and deletion will be separate actions. Any required transaction retention and backup deletion schedule will be disclosed before paid sales open. Current deletion removes the account-linked rows from the live database immediately after successful confirmation.', 'পেমেন্ট এখনো চালু নয়। সাবস্ক্রিপশন চালু হলে বাতিল ও অ্যাকাউন্ট মুছতে আলাদা কাজ করতে হবে। প্রয়োজনীয় লেনদেন ও ব্যাকআপ সংরক্ষণের সময় বিক্রি শুরু হওয়ার আগে জানানো হবে। সফল নিশ্চিতকরণের পরে বর্তমান ডেটাবেসের অ্যাকাউন্ট-সংশ্লিষ্ট তথ্য সঙ্গে সঙ্গে মুছে যায়।')],
  ['privacy', 'SafeNest privacy information', 'SafeNest-এর গোপনীয়তার তথ্য',
    block('Current service · updated 5 October 2026', 'বর্তমান সেবা · ৫ অক্টোবর ২০২৬', 'SafeNest is currently a website and Android development application. This notice describes the current service. Business identity, a verified privacy/support contact and the final retention schedule must be completed before paid public release.', 'SafeNest বর্তমানে একটি ওয়েবসাইট ও Android পরীক্ষামূলক অ্যাপ। এই নোটিশ বর্তমান সেবার তথ্য জানায়। পেইড প্রকাশের আগে ব্যবসার পরিচয়, যাচাইকৃত গোপনীয়তা ও সহায়তার যোগাযোগ এবং চূড়ান্ত তথ্য সংরক্ষণের সময় নির্ধারণ করতে হবে।') +
    block('Accounts and emails', 'অ্যাকাউন্ট ও ইমেইল', 'Supabase processes email, password authentication and sessions. The database stores your optional display name, language and any server-issued protection entitlement. Resend delivers confirmation and recovery emails. The website keeps a login session in browser storage. Never share your password or email reset link.', 'Supabase ইমেইল, পাসওয়ার্ড যাচাই ও লগইন সেশন পরিচালনা করে। ডেটাবেসে ঐচ্ছিক নাম, ভাষা ও সার্ভারের সুরক্ষার অনুমতি থাকে। Resend নিশ্চিতকরণ ও পাসওয়ার্ড রিসেট ইমেইল পাঠায়। ওয়েবসাইট ব্রাউজারে লগইন সেশন রাখে। পাসওয়ার্ড বা রিসেট লিংক শেয়ার করবেন না।') +
    block('Website and DNS', 'ওয়েবসাইট ও DNS', 'Website assets are served through Sites hosting. Google Fonts may receive ordinary web requests. SafeNest checks DNS queries against local rules. Allowed queries reach your network resolver; Cloudflare or Google DNS may be used as fallback. Ordinary UDP/TCP DNS is not encrypted. Configured system Private DNS may use DNS-over-TLS. This build is not a full encrypted VPN and does not inspect decrypted HTTPS page content.', 'Sites হোস্টিং থেকে ওয়েবসাইটের ফাইল আসে। Google Fonts সাধারণ ওয়েব অনুরোধ পেতে পারে। SafeNest স্থানীয় তালিকা দিয়ে DNS অনুরোধ পরীক্ষা করে। অনুমোদিত অনুরোধ নেটওয়ার্কের DNS সেবায় যায়; প্রয়োজনে Cloudflare বা Google DNS ব্যবহৃত হয়। সাধারণ UDP/TCP DNS এনক্রিপ্ট করা নয়। সিস্টেমের Private DNS থাকলে DNS-over-TLS ব্যবহৃত হতে পারে। এটি পুরো এনক্রিপ্টেড VPN নয় এবং HTTPS পৃষ্ঠার খোলা বিষয়বস্তু পরীক্ষা করে না।') +
    block('App guard and local information', 'অ্যাপ গার্ড ও ফোনের তথ্য', 'The current Android development build uses consented Accessibility to identify foreground app package IDs, selected blocked apps, detected VPN apps, supported address bars and narrow Settings/installer labels. A separate consumer Play build is still required and must keep uninstall and permission controls usable. Those observations are not recorded or uploaded. Local lists, check-ins and protection state stay on the phone. No advertising or analytics SDK is included in the current Android source.', 'বর্তমান পরীক্ষামূলক Android সংস্করণ সম্মতির পরে Accessibility দিয়ে অ্যাপের ID, নির্বাচিত ব্লক অ্যাপ, শনাক্ত VPN অ্যাপ, সমর্থিত ঠিকানা ও সীমিত সেটিংস বা ইনস্টলার লেবেল দেখে। আলাদা সাধারণ Play সংস্করণ এখনো তৈরি করতে হবে এবং সেখানে আনইনস্টল ও অনুমতির নিয়ন্ত্রণ খোলা রাখতে হবে। এই পর্যবেক্ষণ সংরক্ষণ বা আপলোড হয় না। স্থানীয় তালিকা, চেক-ইন ও সুরক্ষার অবস্থা ফোনেই থাকে। বর্তমান Android সোর্সে বিজ্ঞাপন বা অ্যানালিটিক্স SDK নেই।') +
    block('Deletion and choices', 'মুছে ফেলা ও আপনার পছন্দ', 'You can request permanent account deletion through the account page without reinstalling the app. It requires password confirmation and deletes the live account, profile and server entitlement. Technical infrastructure may retain operational logs or backups under its configured retention; exact periods must be finalized before launch. SafeNest payments, card collection and crypto checkout are not active.', 'অ্যাপ আবার ইনস্টল না করেই অ্যাকাউন্ট পেজে স্থায়ীভাবে মুছতে পারবেন। পাসওয়ার্ড নিশ্চিত করলে বর্তমান অ্যাকাউন্ট, প্রোফাইল ও সার্ভারের অনুমতি মুছে যাবে। হোস্টিং সেবার নির্ধারিত সময় পর্যন্ত প্রযুক্তিগত লগ বা ব্যাকআপ থাকতে পারে; প্রকাশের আগে সময় নিশ্চিত করতে হবে। SafeNest-এর পেমেন্ট, কার্ড গ্রহণ ও ক্রিপ্টো চেকআউট চালু নয়।') +
    '<p><a href="delete-account.html">' + pair('Delete account instructions', 'অ্যাকাউন্ট মুছে ফেলার নির্দেশিকা') + '</a> · <a href="support.html">' + pair('Service help', 'সেবার সহায়তা') + '</a></p>'],
  ['terms', 'SafeNest service terms and status', 'SafeNest-এর শর্ত ও বর্তমান অবস্থা',
    block('Development service', 'পরীক্ষামূলক সেবা', 'The website is live and the Android application is under testing. Pricing is proposed; purchases and automatic renewals are not active. Do not rely on this development build as your only protection. It cannot promise that every gambling site, adult site, VPN or proxy is blocked.', 'ওয়েবসাইট চালু এবং Android অ্যাপ পরীক্ষাধীন। মূল্য প্রস্তাবিত; কেনা বা স্বয়ংক্রিয় নবায়ন চালু নয়। পরীক্ষামূলক অ্যাপকে একমাত্র সুরক্ষা ধরে নেবেন না। সব জুয়া, প্রাপ্তবয়স্ক সাইট, VPN বা প্রক্সি ব্লক হওয়ার প্রতিশ্রুতি নেই।') +
    block('Permission and finite protection', 'অনুমতি ও নির্দিষ্ট মেয়াদের সুরক্ষা', 'Protection requires separate informed consent and a server-verified active period. Once started, this app has no in-app pause during that period and expires automatically. Android may revoke permissions or stop the application. A future consumer Play build must leave uninstall and Settings controls usable. Managed-device controls require separate authorized enrollment.', 'সুরক্ষা চালু করতে আলাদা সচেতন সম্মতি ও সার্ভারে যাচাইকৃত মেয়াদ দরকার। চালুর পরে অ্যাপে বিরতি নেই এবং মেয়াদ শেষে স্বয়ংক্রিয়ভাবে শেষ হয়। Android অনুমতি ফিরিয়ে নিতে বা অ্যাপ বন্ধ করতে পারে। ভবিষ্যতের সাধারণ Play সংস্করণে আনইনস্টল ও সেটিংস খোলা রাখতে হবে। পরিচালিত ডিভাইসের নিয়ন্ত্রণের জন্য আলাদা অনুমোদিত নিবন্ধন লাগে।') +
    block('Before paid launch', 'পেইড প্রকাশের আগে', 'Final seller identity, support contact, prices, taxes, device limits, cancellation/refund rules and transaction retention must be published before checkout opens. No payment reference or success page alone can activate protection; the server must verify the payment provider receipt.', 'চেকআউট চালুর আগে বিক্রেতার পরিচয়, সহায়তার যোগাযোগ, মূল্য, কর, ডিভাইস সীমা, বাতিল ও রিফান্ডের নিয়ম এবং লেনদেন সংরক্ষণের সময় প্রকাশ করতে হবে। শুধু পেমেন্ট নম্বর বা সফল পেজ দিয়ে সুরক্ষা চালু হবে না; সার্ভারে পেমেন্ট সেবার রসিদ যাচাই করতে হবে।')],
  ['checkout', 'SafeNest payments', 'SafeNest পেমেন্ট',
    block('Checkout is not open yet', 'চেকআউট এখনো চালু নয়', 'No payment is collected on this page. Proposed monthly and annual prices are on the pricing page. We will open checkout only after verified receipts, refunds, cancellation and activation have been tested.', 'এই পেজে পেমেন্ট নেওয়া হয় না। প্রস্তাবিত মাসিক ও বার্ষিক মূল্য মূল্যতালিকায় আছে। রসিদ যাচাই, রিফান্ড, বাতিল ও সুরক্ষা চালু করার পরীক্ষা শেষ হলে চেকআউট খুলবে।') +
    block('Planned payment options', 'পরিকল্পিত পেমেন্ট মাধ্যম', 'International cards and Bangladesh mobile wallets such as bKash, Nagad, Rocket and upay need an approved merchant/payment gateway account. Logos show planned methods, not live integrations. Cryptocurrency is not currently accepted. The Android development app currently serves existing accounts and has no purchase button.', 'আন্তর্জাতিক কার্ড এবং bKash, Nagad, Rocket ও upay-এর জন্য অনুমোদিত মার্চেন্ট বা পেমেন্ট গেটওয়ে অ্যাকাউন্ট দরকার। লোগো পরিকল্পিত মাধ্যম দেখায়; সংযোগ চালু নয়। ক্রিপ্টোকারেন্সি বর্তমানে গ্রহণ করা হয় না। পরীক্ষামূলক Android অ্যাপ বিদ্যমান অ্যাকাউন্ট ব্যবহার করে; অ্যাপে কেনার বোতাম নেই।') +
    '<p><a class="btn dark" href="pricing.html">' + pair('View proposed plans', 'প্রস্তাবিত প্ল্যান দেখুন') + '</a></p>'],
  ['support', 'SafeNest help and release status', 'SafeNest সহায়তা ও প্রকাশের অবস্থা',
    block('If ordinary browsing stops', 'সাধারণ ব্রাউজিং বন্ধ হলে', 'This DNS-only build must leave Android’s “Block connections without VPN” off. Test a normal website and a listed test domain on both Wi-Fi and mobile data. Another active VPN can replace SafeNest on a personal phone; the status screen should report it.', 'এই DNS-only সংস্করণে Android-এর “Block connections without VPN” বন্ধ রাখতে হবে। Wi-Fi ও মোবাইল ডেটায় সাধারণ সাইট ও তালিকার পরীক্ষার ডোমেইন দেখুন। ব্যক্তিগত ফোনে অন্য সক্রিয় VPN SafeNest-কে বদলে দিতে পারে; অবস্থা পেজে তা দেখানোর কথা।') +
    block('Account access', 'অ্যাকাউন্ট ব্যবহার', 'Use the account page to confirm your email, reset a forgotten password or delete the account. A verified support contact will be published before paid release. Never send passwords, authentication tokens or private browsing details in public comments.', 'অ্যাকাউন্ট পেজে ইমেইল নিশ্চিত করুন, ভুলে যাওয়া পাসওয়ার্ড রিসেট করুন বা অ্যাকাউন্ট মুছুন। পেইড প্রকাশের আগে যাচাইকৃত সহায়তার যোগাযোগ দেওয়া হবে। পাবলিক মন্তব্যে পাসওয়ার্ড, লগইন টোকেন বা ব্যক্তিগত ব্রাউজিংয়ের তথ্য দেবেন না।') +
    '<p><a href="account.html">' + pair('Open my account', 'আমার অ্যাকাউন্ট খুলুন') + '</a> · <a href="delete-account.html">' + pair('Delete my account', 'আমার অ্যাকাউন্ট মুছুন') + '</a></p>']
];
for (const [slug, title, bn, body] of pages) {
  await writeFile(`dist/${slug}.html`, `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="referrer" content="no-referrer"><title>${escape(title)}</title><link rel="icon" href="favicon.svg"><link rel="stylesheet" href="styles.css"><link rel="stylesheet" href="liquid-pink.css"></head><body>${header}<main class="page-body" id="main"><section class="page-intro"><h1>${pair(title,bn)}</h1></section>${body}</main>${footer}<script src="app.js" defer></script><script src="liquid-pink.js" defer></script></body></html>`);
}
const legal = `<nav aria-label="Service information"><a href="privacy.html">${pair('Privacy','গোপনীয়তা')}</a><a href="terms.html">${pair('Terms','শর্তাবলি')}</a><a href="delete-account.html">${pair('Delete account','অ্যাকাউন্ট মুছুন')}</a><a href="support.html">${pair('Help','সহায়তা')}</a></nav>`;
for (const file of await readdir('dist')) {
  if (!file.endsWith('.html') || file === 'account.html') continue;
  const path = `dist/${file}`;
  const html = (await readFile(path, 'utf8')).replaceAll('href="./#privacy"', 'href="privacy.html"').replace('</footer>', `${legal}</footer>`);
  await writeFile(path, html);
}
